


"""
Django settings for equipment_health project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-请在这里换成你自己的密钥（随便打一段就行）'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True   # ← 必须是 True，否则会出现 ALLOWED_HOSTS 错误

ALLOWED_HOSTS = [
    '*',
    '10.120.204.90',
    '10.178.71.31',
    '10.177.167.48',
    'localhost',
    '127.0.0.1',
]

# 确保协议头正确，且末尾绝对不要加 / 斜杠
CSRF_TRUSTED_ORIGINS = [
    'http://10.120.204.90',
    'http://10.120.204.90:8000',
    'http://10.177.167.48',
    'http://10.177.167.48:8000',
    'http://10.178.71.31',
    'http://10.178.71.31:8000',
    'http://localhost',
    'http://127.0.0.1',
]


CSRF_COOKIE_SECURE = False
CSRF_USE_SESSIONS = False


# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # === 你已经成功的 App（只保留这些）===
    'core.apps.CoreConfig',
    'design.apps.DesignConfig',
    'issues.apps.IssuesConfig',
    'spares.apps.SparesConfig',
     'alerts.apps.AlertsConfig',
    # 报警模块我们先不加，等你确认其他页
    'maintenance.apps.MaintenanceConfig',
     'data.apps.DataConfig',
     'personnel.apps.PersonnelConfig',
     'performance.apps.PerformanceConfig',
      'search.apps.SearchConfig',#搜搜来了
    'production.apps.ProductionConfig',#layout排布
    'notification',#邮件发送
    'users',          # ← 新增这一行
    'laser_check',  # ← 新增这一行
     'patrol_analytics',

]

MIDDLEWARE = [

    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',   # ← 一定要在第二位
    'django.contrib.sessions.middleware.SessionMiddleware',
     'django.middleware.locale.LocaleMiddleware',# ← 新增这一行（关键！）
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'equipment_health.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],   # ← 你的模板文件夹
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'equipment_health.wsgi.application'

# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# Internationalization
LANGUAGE_CODE = 'zh-hans'   # 中文
# 支持的语言
LANGUAGES = [
    ('zh-hans', '中文'),
    ('vi', 'Tiếng Việt'),
    ('en', 'English'),
]

TIME_ZONE = 'Asia/Shanghai'
USE_I18N = True
USE_L10N = True

USE_TZ = True

# 翻译文件存放位置
import os
LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),
]



# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'   # 收集静态文件的目录
STATICFILES_DIRS = [BASE_DIR / 'static']   # 如果你有 static 文件夹

STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'
WHITENOISE_MAX_AGE =31536000 #静态文件保存1年

# ==================== 【新增】collectstatic 收集目录 pdjs====================
STATIC_ROOT = BASE_DIR / 'staticfiles'     # ←←← 关键一行！必须加

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ==================== Media files (照片上传) ====================
import os
from pathlib import Path
BASE_DIR = Path(__file__).resolve().parent.parent

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# ==================== 媒体文件配置（照片真正保存） ====================
import os
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

# 开发环境让照片能访问
if DEBUG:
    from django.conf.urls.static import static
    # （后面会在主urls.py里加）



# # ==================== Outlook / Office 365 配置 ====================
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
#
# EMAIL_HOST = 'smtp.office365.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True          # 必须开启TLS
# EMAIL_USE_SSL = False
#
# EMAIL_HOST_USER = '你的公司邮箱@公司域名.com'     # ← 改成你的完整邮箱
# EMAIL_HOST_PASSWORD = '你的密码或应用密码'         # ← 改成对应密码
#
# DEFAULT_FROM_EMAIL = '设备健康度管理系统 <你的公司邮箱@公司域名.com>'

# ==================== 163邮箱配置（已按你的邮箱修正） ====================
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'   # 临时测试模式

EMAIL_HOST = 'smtp.163.com'
EMAIL_PORT = 465
EMAIL_USE_SSL = True
EMAIL_USE_TLS = False

EMAIL_HOST_USER = 'ugboss@163.com'                  # 你的163邮箱
EMAIL_HOST_PASSWORD = 'NZhikxpS6QgeGwvv'            # 你的授权码

# 关键：发件人必须和你登录的邮箱一致
DEFAULT_FROM_EMAIL = '设备健康度管理系统 <ugboss@163.com>'

EMAIL_TIMEOUT = 10

# ==================== 登录后跳转设置 默认界面 ====================
LOGIN_REDIRECT_URL = 'core:equipment_list'      # 登录成功后跳转到设备总表
LOGOUT_REDIRECT_URL = 'login'                   # 登出后跳转到登录页


