# Generated by Django 4.2.7 on 2026-04-18 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LaserCheckConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_folder', models.CharField(max_length=500, verbose_name='产品图文件夹路径')),
                ('laser_folder', models.CharField(max_length=500, verbose_name='镭雕图文件夹路径')),
                ('mapping_excel', models.CharField(blank=True, max_length=500, verbose_name='料号映射Excel路径')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '镭雕图检查配置',
                'verbose_name_plural': '镭雕图检查配置',
            },
        ),
    ]
