# Generated by Django 4.2.7 on 2026-04-22 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('laser_check', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(db_index=True, max_length=50, verbose_name='料号')),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='ai_compare/product/%Y/%m/%d/', verbose_name='产品图截图')),
                ('laser_image', models.ImageField(blank=True, null=True, upload_to='ai_compare/laser/%Y/%m/%d/', verbose_name='镭雕图截图')),
                ('result_text', models.TextField(verbose_name='AI检测结果')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='检测时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='检测人员')),
            ],
            options={
                'verbose_name': 'AI检测记录',
                'verbose_name_plural': 'AI检测记录',
                'ordering': ['-created_at'],
            },
        ),
    ]
