# Generated by Django 4.2.7 on 2026-03-19 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_equipment_area_equipment_category_equipment_eq_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_code', models.CharField(max_length=50, verbose_name='问题码')),
                ('desc', models.TextField(verbose_name='异常现象及原因')),
                ('occur_date', models.DateField(verbose_name='发生日期')),
                ('severity', models.IntegerField(choices=[(1, '低'), (2, '中'), (3, '高')], default=2)),
                ('root_cause', models.TextField(blank=True, verbose_name='处理方法')),
                ('reoccur_status', models.BooleanField(default=False, verbose_name='再次发生')),
                ('source_excel', models.CharField(blank=True, max_length=200)),
                ('abnormal_work_time', models.IntegerField(default=0, verbose_name='异常工时(min)')),
                ('work_time_type', models.CharField(blank=True, max_length=20, verbose_name='异常工时甄别(硬件/软件/其它)')),
                ('can_import_maintenance', models.BooleanField(default=False, verbose_name='可否导入保养')),
                ('maintenance_id', models.CharField(blank=True, max_length=50, verbose_name='保养ID')),
                ('maintenance_content', models.TextField(blank=True, verbose_name='保养内容')),
                ('can_import_design', models.BooleanField(default=False, verbose_name='可否导入设计改善')),
                ('design_id', models.CharField(blank=True, max_length=50, verbose_name='设计ID')),
                ('design_content', models.TextField(blank=True, verbose_name='设计内容')),
                ('can_import_training', models.BooleanField(default=False, verbose_name='可否导入人员培训')),
                ('training_id', models.CharField(blank=True, max_length=50, verbose_name='培训ID')),
                ('training_content', models.TextField(blank=True, verbose_name='培训内容')),
                ('can_import_repair', models.BooleanField(default=False, verbose_name='可否导入现场维修改善')),
                ('repair_id', models.CharField(blank=True, max_length=50, verbose_name='维修ID')),
                ('repair_content', models.TextField(blank=True, verbose_name='维修内容')),
                ('risk_id', models.CharField(blank=True, max_length=50, verbose_name='RISK ID')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='core.equipment')),
            ],
        ),
    ]
