# Generated by Django 4.2.7 on 2026-03-25 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatrolIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField(blank=True, null=True, verbose_name='顺序')),
                ('date', models.DateField(verbose_name='日期')),
                ('line', models.CharField(max_length=50, verbose_name='线别')),
                ('station', models.CharField(max_length=50, verbose_name='站别')),
                ('problem_desc', models.TextField(verbose_name='问题要改善')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='patrol_photos/', verbose_name='照片')),
                ('op_responsible', models.CharField(max_length=100, verbose_name='越南负责人（OP）')),
                ('supervisor', models.CharField(max_length=100, verbose_name='责任单位主管')),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default='Open', max_length=10, verbose_name='情况')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '点检问题点记录',
                'verbose_name_plural': '点检问题点记录',
                'ordering': ['-date'],
            },
        ),
    ]
