# Generated by Django 4.2.7 on 2026-03-25 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_patrolissue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patrolissue',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='patrol_photos/', verbose_name='照片/视频'),
        ),
    ]
