# Generated by Django 4.2.7 on 2026-03-29 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_alter_patrolissue_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='patrolissue',
            name='photos',
            field=models.JSONField(blank=True, default=list, verbose_name='照片列表（多张）'),
        ),
        migrations.AlterField(
            model_name='patrolissue',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='patrol_photos/', verbose_name='照片/视频（单张兼容）'),
        ),
    ]
