# Generated by Django 4.2.7 on 2026-03-30 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0004_patrolissue_photos_alter_patrolissue_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentissue',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='issues_photos/', verbose_name='照片/视频（单张兼容）'),
        ),
        migrations.AddField(
            model_name='equipmentissue',
            name='photos',
            field=models.JSONField(blank=True, default=list, verbose_name='照片列表（多张）'),
        ),
    ]
