# Generated by Django 4.2.7 on 2026-08-02 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0005_equipmentissue_photo_equipmentissue_photos'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatrolCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='类别名称')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序（数字越小越靠前）')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '点检类别',
                'verbose_name_plural': '点检类别',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='patrolissue',
            name='spare_field_1',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='备用字段1'),
        ),
        migrations.AddField(
            model_name='patrolissue',
            name='spare_field_2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='备用字段2'),
        ),
        migrations.AddField(
            model_name='patrolissue',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='issues.patrolcategory', verbose_name='点检类别'),
        ),
    ]
