# Generated by Django 4.2.7 on 2026-08-02 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0006_patrolcategory_patrolissue_spare_field_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarqueeNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200, verbose_name='通知内容')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_by', models.CharField(blank=True, max_length=50, verbose_name='发布人')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '公屏通知',
                'verbose_name_plural': '公屏通知',
                'ordering': ['-created_at'],
            },
        ),
    ]
