# Generated by Django 4.2.7 on 2026-08-15 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0007_marqueenotice'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentIssueCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='类别名称')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序（数字越小越靠前）')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '设备异常问题类别',
                'verbose_name_plural': '设备异常问题类别',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='equipmentissue',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_issues', to='issues.equipmentissuecategory', verbose_name='问题类别'),
        ),
    ]
