# Generated by Django 4.2.7 on 2026-08-15 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0008_equipmentissuecategory_equipmentissue_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentissue',
            name='spare_field_1',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='备用字段1'),
        ),
        migrations.AddField(
            model_name='equipmentissue',
            name='spare_field_2',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='备用字段2'),
        ),
        migrations.AddField(
            model_name='equipmentissue',
            name='spare_field_3',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='备用字段3'),
        ),
        migrations.AddField(
            model_name='equipmentissue',
            name='supervisor',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='责任主管'),
        ),
    ]
