# Generated by Django 4.2.7 on 2026-08-16 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0009_equipmentissue_spare_field_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionLineConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(max_length=50, verbose_name='机种')),
                ('category', models.CharField(max_length=50, verbose_name='类别')),
                ('line', models.CharField(max_length=50, verbose_name='线体')),
                ('supervisor', models.CharField(blank=True, default='', max_length=100, verbose_name='默认主管')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('remark', models.CharField(blank=True, default='', max_length=200, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '产线层级配置',
                'verbose_name_plural': '产线层级配置',
                'ordering': ['order', 'model_type', 'category', 'line'],
                'unique_together': {('model_type', 'category', 'line')},
            },
        ),
    ]
