# Generated by Django 4.2.7 on 2026-03-19 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_equipment_area_equipment_category_equipment_eq_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_computer', models.BooleanField(default=False, verbose_name='工业电脑')),
                ('has_robot_arm', models.BooleanField(default=False, verbose_name='机械手')),
                ('has_screw_feeder', models.BooleanField(default=False, verbose_name='螺丝供料器')),
                ('has_scanner', models.BooleanField(default=False, verbose_name='扫描仪')),
                ('has_printer', models.BooleanField(default=False, verbose_name='打印机')),
                ('vision_type', models.CharField(choices=[('AI', 'AI视觉'), ('normal', '普通视觉'), ('none', '无')], default='none', max_length=20, verbose_name='视觉类型')),
                ('plc_model', models.CharField(blank=True, max_length=100, verbose_name='PLC型号')),
                ('dvp_file', models.FileField(blank=True, upload_to='design/dvp/', verbose_name='DVP文件')),
                ('pmp_file', models.FileField(blank=True, upload_to='design/pmp/', verbose_name='PMP文件')),
                ('image', models.ImageField(blank=True, null=True, upload_to='designs/', verbose_name='设备照片')),
                ('risk_points_text', models.TextField(blank=True, verbose_name='风险点描述')),
                ('vulnerable_parts_list', models.TextField(blank=True, verbose_name='易损部件列表')),
                ('software_risks', models.TextField(blank=True, verbose_name='软件风险')),
                ('has附属', models.BooleanField(default=False, verbose_name='有附属')),
                ('has_scan', models.BooleanField(default=False, verbose_name='有扫码')),
                ('multi_model', models.BooleanField(default=False, verbose_name='多机种')),
                ('perf_req', models.CharField(blank=True, max_length=200, verbose_name='性能要求')),
                ('novel_design', models.BooleanField(default=False, verbose_name='新特异设计')),
                ('equipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='design_info', to='core.equipment')),
            ],
        ),
    ]
