# Generated by Django 4.2.7 on 2026-03-18 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='设备编号')),
                ('name', models.CharField(max_length=100, verbose_name='设备名称')),
                ('model', models.CharField(max_length=100, verbose_name='型号')),
                ('location', models.CharField(max_length=200, verbose_name='位置')),
                ('install_date', models.DateField(verbose_name='安装日期')),
                ('status', models.CharField(choices=[('active', '活跃'), ('inactive', '停用'), ('maintenance', '保养中')], default='active', max_length=20, verbose_name='状态')),
                ('responsible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
            ],
        ),
        migrations.CreateModel(
            name='AlarmRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alarm_type', models.CharField(choices=[('red_light', '红灯报警'), ('sensor', '传感器异常'), ('other', '其他')], max_length=50, verbose_name='报警类型')),
                ('level', models.IntegerField(default=1, verbose_name='严重等级')),
                ('occur_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('未处理', '未处理'), ('已处理', '已处理')], default='未处理', max_length=20)),
                ('desc', models.TextField(blank=True, verbose_name='描述')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarms', to='core.equipment')),
                ('handler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
