# Generated by Django 4.2.7 on 2026-03-19 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='area',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='区域'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='类别'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='eq_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='设备类型'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='line',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='线别'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='model_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='机种'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='rfid_card',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='RFID卡号'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='station',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='站别'),
        ),
    ]
