# Generated by Django 4.2.7 on 2026-03-22 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_equipment_area_equipment_category_equipment_eq_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='position',
            field=models.IntegerField(default=0, verbose_name='产线位置排序'),
        ),
    ]
