# Generated by Django 4.2.7 on 2026-03-24 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_equipment_position'),
    ]

    operations = [
    ]
