# Generated by Django 4.2.7 on 2026-03-24 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20260324_2147'),
    ]

    operations = [
    ]
