# Generated by Django 4.2.7 on 2026-03-25 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20260324_2149'),
    ]

    operations = [
    ]
