# Generated by Django 4.2.7 on 2026-04-05 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_equipment_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='ai_fault_prob',
            field=models.FloatField(default=0, verbose_name='下周故障概率(%)'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='ai_last_predict',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最后预测时间'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='ai_remaining_life',
            field=models.IntegerField(default=0, verbose_name='剩余寿命(天)'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='ai_score',
            field=models.FloatField(default=0, verbose_name='龙虾AI健康度'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='ai_suggestion',
            field=models.TextField(blank=True, verbose_name='龙虾AI建议'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='ai_top_risks',
            field=models.JSONField(blank=True, default=list, verbose_name='主要风险模块'),
        ),
    ]
