# Generated by Django 4.2.7 on 2026-04-07 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_equipment_ai_fault_prob_equipment_ai_last_predict_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_number', models.CharField(max_length=50, unique=True, verbose_name='工号')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='姓名')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='部门/职能')),
                ('line', models.CharField(blank=True, max_length=100, verbose_name='负责线体')),
                ('role', models.CharField(choices=[('admin', '管理员'), ('user', '普通用户')], default='user', max_length=10, verbose_name='用户角色')),
                ('permission_area', models.CharField(blank=True, max_length=100, verbose_name='权限领域')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户扩展信息',
                'verbose_name_plural': '用户扩展信息',
            },
        ),
    ]
