# Generated by Django 4.2.7 on 2026-03-18 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonnelInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='开始看护日期')),
                ('equip_duration', models.IntegerField(default=0, verbose_name='设备看护时长(月)')),
                ('skills_list', models.TextField(blank=True, verbose_name='可处理异常技能')),
                ('training_history', models.TextField(blank=True, verbose_name='培训记录')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personnel', to='core.equipment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='看护人员')),
            ],
        ),
    ]
