# Generated by Django 4.2.7 on 2026-03-19 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_equipment_area_equipment_category_equipment_eq_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='备品名称')),
                ('spec', models.CharField(max_length=100, verbose_name='规格')),
                ('supplier', models.CharField(blank=True, max_length=100, verbose_name='品牌')),
                ('stock_qty', models.IntegerField(default=0, verbose_name='庫存數量')),
                ('min_stock', models.IntegerField(default=5, verbose_name='安全庫存')),
                ('usage_qty', models.IntegerField(default=0, verbose_name='當站使用數量')),
                ('life_months', models.IntegerField(default=30, verbose_name='使用壽命(月)')),
                ('difference', models.IntegerField(default=0, verbose_name='差異')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spares', to='core.equipment')),
            ],
        ),
    ]
