# Generated by Django 4.2.7 on 2026-03-31 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spares', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sparepart',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='spares_photos/', verbose_name='照片'),
        ),
        migrations.AddField(
            model_name='sparepart',
            name='photos',
            field=models.JSONField(blank=True, default=list, verbose_name='照片列表（多张）'),
        ),
    ]
