# Generated by Django 4.2.7 on 2026-04-18 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailgroup',
            name='emails',
            field=models.TextField(verbose_name='邮箱列表（一行一个或逗号分隔）'),
        ),
    ]
