# Generated by Django 4.2.7 on 2026-03-18 19:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(choices=[('vibration', '振动值'), ('ct', 'CT值'), ('temperature', '温度'), ('pressure', '压力')], max_length=20, verbose_name='数据类型')),
                ('value', models.FloatField(verbose_name='测量值')),
                ('unit', models.CharField(default='mm/s', max_length=20, verbose_name='单位')),
                ('record_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='记录时间')),
                ('note', models.CharField(blank=True, max_length=100)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_records', to='core.equipment')),
            ],
        ),
    ]
