# Generated by Django 4.2.7 on 2026-05-09 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatrolSummaryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('save_date', models.DateTimeField(auto_now_add=True, verbose_name='保存时间')),
                ('start_date', models.DateField(verbose_name='数据开始日期')),
                ('end_date', models.DateField(verbose_name='数据结束日期')),
                ('data', models.JSONField(verbose_name='汇总数据')),
            ],
            options={
                'verbose_name': '点检汇总记录',
                'verbose_name_plural': '点检汇总记录',
                'ordering': ['-save_date'],
            },
        ),
    ]
