# Generated by Django 4.2.7 on 2026-03-22 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_equipment_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='产线名称')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='描述')),
            ],
        ),
        migrations.CreateModel(
            name='LineEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0, verbose_name='排序位置')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_positions', to='core.equipment')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_equipments', to='production.line')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('line', 'equipment')},
            },
        ),
    ]
