# Generated by Django 4.2.7 on 2026-03-18 20:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calc_date', models.DateField(default=django.utils.timezone.now, verbose_name='计算日期')),
                ('mtbf', models.FloatField(default=0, verbose_name='MTBF(小时)')),
                ('mttr', models.FloatField(default=0, verbose_name='MTTR(小时)')),
                ('oee', models.FloatField(default=0, verbose_name='OEE(%)')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_kpis', to='core.equipment')),
            ],
        ),
    ]
