# Generated by Django 4.2.7 on 2026-03-18 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('red_light', '红灯报警'), ('error_code', '错误代码'), ('sensor', '传感器异常'), ('other', '其他')], max_length=50, verbose_name='报警类型')),
                ('desc', models.TextField(verbose_name='报警描述')),
                ('occur_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='发生时间')),
                ('handled', models.BooleanField(default=False, verbose_name='是否处理')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='core.equipment')),
                ('handler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='处理人')),
            ],
        ),
    ]
