# Generated by Django 4.2.7 on 2026-03-18 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_type', models.CharField(choices=[('daily', '日常保养'), ('weekly', '周保养'), ('monthly', '月保养'), ('quarterly', '季度保养'), ('yearly', '年度保养')], max_length=50, verbose_name='保养类型')),
                ('desc', models.TextField(verbose_name='保养内容/描述')),
                ('maintenance_date', models.DateField(default=django.utils.timezone.now, verbose_name='保养日期')),
                ('next_due_date', models.DateField(verbose_name='下次到期日期')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='core.equipment')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='执行人')),
            ],
        ),
    ]
