# Generated by Django 4.2.7 on 2026-03-20 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_equipment_area_equipment_category_equipment_eq_type_and_more'),
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceSOP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='保养项目名称')),
                ('category', models.CharField(choices=[('daily', '日常保养'), ('weekly', '周保养'), ('monthly', '月保养'), ('quarterly', '季度保养'), ('half_year', '半年保养')], max_length=20, verbose_name='保养类别')),
                ('is_numeric', models.BooleanField(default=False, verbose_name='是否需要数值')),
                ('lower_limit', models.FloatField(blank=True, null=True, verbose_name='下限')),
                ('upper_limit', models.FloatField(blank=True, null=True, verbose_name='上限')),
                ('unit', models.CharField(blank=True, max_length=20, verbose_name='单位')),
                ('responsible_unit', models.CharField(blank=True, max_length=50, verbose_name='保养负责人单位')),
                ('sop_photos', models.JSONField(blank=True, default=list, verbose_name='SOP照片URL列表')),
                ('sop_document', models.FileField(blank=True, null=True, upload_to='sops/docs/', verbose_name='SOP文档')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sops', to='core.equipment', verbose_name='所属设备')),
            ],
        ),
    ]
