# Generated by Django 4.2.7 on 2026-03-22 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_maintenancejobtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancesop',
            name='sop_image',
            field=models.ImageField(blank=True, null=True, upload_to='sop_images/', verbose_name='SOP图片'),
        ),
        migrations.DeleteModel(
            name='MaintenanceJobTemplate',
        ),
    ]
