# Generated by Django 4.2.7 on 2026-03-22 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_equipment_area_equipment_category_equipment_eq_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maintenance', '0004_maintenancesop_sop_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceJobTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_date', models.DateField(verbose_name='执行日期')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('done', '已完成')], default='pending', max_length=20)),
                ('before_photo', models.ImageField(blank=True, null=True, upload_to='jobs/before/', verbose_name='执行前照片')),
                ('after_photo', models.ImageField(blank=True, null=True, upload_to='jobs/after/', verbose_name='执行后照片')),
                ('tool_life', models.CharField(blank=True, max_length=50, verbose_name='起子头/吸盘寿命')),
                ('spare_used', models.BooleanField(default=False, verbose_name='是否使用备品')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='稽核人')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_templates', to='core.equipment')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='执行人')),
                ('sop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='maintenance.maintenancesop')),
            ],
        ),
    ]
